config/routes.rb
Rails.application.routes.draw do
  
  root 'bills#index', as: 'root_path'
  
  devise_for :accounts, :controllers => {registrations: 'registrations' }
  
  resources :users
  resources :bills do
    resources :charges, only: [:create, :new, :edit, :update, :destroy]
  end
  get 'bills/:id/send', to: 'bills#send_bill', as: :send_bill
  get 'users/:id/send', to: 'users#send_reminder', as: :send_reminder
  get 'settings', to: 'accounts#settings', as: :settings
  get 'reports', to: 'accounts#reports', as: :reports
  
  resources :charts, only: [] do
    collection do
      get 'bill_total_by_month'
      get 'user_charge_chart'
      get 'user_balance_chart'
    end
  end
  
end

app/models/user.rb
class User < ActiveRecord::Base
  #t.string :name
  #t.string :email
  #t.references :account, index: true, foreign_key: true
  #t.text :message
  #t.decimal :balance, scale: 2, precision: 6
  
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :name, presence: true, length: { maximum: 25 }
  validates :email, presence: true, length: { maximum: 50 },
    format: { with: VALID_EMAIL_REGEX }
  has_many :charges, dependent: :destroy
  belongs_to :account
  belongs_to :user, :foreign_key => 'manager_id'

  def a_manager?
    User.where('manager_id = ?', id).any?
  end

  def managed
    User.where('manager_id = ?', id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_account!
  before_action :correct_account, only: [:edit, :show, :destroy, :update, 
    :send_reminder]
    
  def index
    @users = User.where(:account_id => current_account.id)
  end
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "User created!"
      redirect_to users_url
    else
      render 'new'
    end
  end
  
  def show
    @user=User.find(params[:id])
    @charges = @user.charges.order(date: :desc).page(params[:page])
  end
  
  def edit
    @user=User.find(params[:id])
  end
  
  def update
    @user=User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "User updated!"
      redirect_to users_url
    else
      render 'edit'
    end
  end
  
  def destroy
    @user=User.find(params[:id])
    @user.destroy
    flash[:success] = "User deleted."
    redirect_to users_url
  end
  
  def send_reminder
    @user = User.find(params[:id])
    UserMailer.mail_reminder(@user).deliver_later
    flash[:success] = "Reminder sent!"
    redirect_to @user
  end
  
  private
  
    def user_params
      params.require(:user).permit(:name, :email, :message, :account_id, 
        :balance, :manager_id)
    end
    
    def correct_account
      @user = User.find(params[:id])
      unless @user.account_id == current_account.id
        flash[:warning] = "That user doesn't belong to you!"
        redirect_to root_path_url
      end
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_user.html.erb
<tr>
  <td><%= link_to user.name, user_url(user.id) %></td>
  <td><%= number_to_currency(user.balance) %></td>
  <td><%= user.email %></td>
</tr>

app/views/users/edit.html.erb
<% # users/edit %>
<div class="container">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <h1 class="text-center">Edit User</h1>
      <%= form_for (@user) do |f| %>
        <%= render 'shared/form_errors', item: @user %>
        <div class="form-group">
          <%= f.label :name %>
          <%= f.text_field :name, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :email %>
          <%= f.text_field :email, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :manager, "Manager (optional)" %><br>
          <%= f.select(:manager_id, User.where(:account_id => current_account.id).collect {|p| [ p.name, p.id ] }, {include_blank: ""}) %>
        </div>
        <div class="form-group">
          <%= f.label :message, "Custom email signature (optional)" %>
          <%= f.text_area :message, class: "form-control" %>        
        </div>
        <%= f.submit class: 'btn btn-success' %>
        <%= link_to "Cancel", :back, class: "btn btn-default pull-right" %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container">
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <h1 class="text-center">Users Dashboard</h1>
            <% if @users.present? %>
              <%= user_balance_chart %>
            <% end %>
            <br><br>
            <%= link_to "New User", new_user_url, class: "btn btn-primary" %>
            <% if @users.present? %>
              <table class="table table-hover">
                <thead>
                  <tr class="text-center">
                    <th>Name</th>
                    <th>Balance</th>
                    <th>Email Address</th>
                  </tr>
                </thead>
                <tbody>
                  <%= render @users %>
                </tbody>
              </table>
            <% else %>
              <p><br>You haven't entered any users yet.</p>
            <% end %>
        </div>
    </div>
</div>

app/views/users/new.html.erb
<% # users/edit %>
<div class="container">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <h1 class="text-center">New User</h1>
      <%= form_for (@user) do |f| %>
        <%= render 'shared/form_errors', item: @user %>
        <%= f.text_field :name, placeholder: "Name",
            class: "form-control" %><br />
        <%= f.text_field :email, placeholder: "Email", 
            class: "form-control" %><br />
        <%= f.text_area :message, 
            placeholder: "Custom email signature (optional)",
            class: "form-control" %><br />
        <%= f.hidden_field :account_id, :value => current_account.id %>
        <%= f.hidden_field :balance, :value => '0.00' %>
        <%= f.submit class: 'btn btn-success' %>
        <%= link_to "Cancel", :back, class: "btn btn-default pull-right" %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<% #users/show %>
<div class="container">
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
          <h1 class="text-center"><%= @user.name %></h1>
          <%= link_to "Edit User Info", edit_user_url, 
              class: "btn btn-primary" %>
           <%= link_to "Send Reminder", send_reminder_url,
                       class: "btn btn-primary",
                       data: { confirm: "Send reminder of unpaid charges?" } %>
          <%= link_to "Delete User", @user, method: :delete, 
              class: "btn btn-danger pull-right", 
              data: { confirm: "Delete #{@user.name}?" } %>
          
          <% if @user.charges.present? %>
            <%= user_charge_chart %>
            <table class="table table-striped">
              <thead>
                <tr class="text-center">
                  <th>Bill Date</th>
                  <th>Data Used</th>
                  <th>Amount Due</th>
                  <th>Status</th>
                </tr>
              </thead>
              <tbody>
                <%= render @charges, selector: "short" %>
              </tbody>
            </table>
              <%= paginate @charges %>
          <% else %>
            <p><br/>You haven't entered any charges for this user yet.</p>
          <% end %>
        </div>
    </div>
</div>