config/routes.rb
Rails.application.routes.draw do
  
  root 'bills#index', as: 'root_path'
  
  devise_for :accounts, :controllers => {registrations: 'registrations' }
  
  resources :users
  resources :bills do
    resources :charges, only: [:create, :new, :edit, :update, :destroy]
  end
  get 'bills/:id/send', to: 'bills#send_bill', as: :send_bill
  get 'users/:id/send', to: 'users#send_reminder', as: :send_reminder
  get 'settings', to: 'accounts#settings', as: :settings
  get 'reports', to: 'accounts#reports', as: :reports
  
  resources :charts, only: [] do
    collection do
      get 'bill_total_by_month'
      get 'user_charge_chart'
      get 'user_balance_chart'
    end
  end
  
end

app/models/bill.rb
class Bill < ActiveRecord::Base
  #t.date :date
  #t.decimal :amount, precision: 6, scale: 2
  #t.decimal :total_data, precision: 6, scale: 3
  #t.decimal :data_cost, precision: 6, scale: 2 
  #t.references :account, index: true, foreign_key: true, :null => false
  #t.decimal :balance, precision: 6, scale: 2
  #t.decimal :data_subtotal, precision: 6, scale: 3
  #t.decimal :percent_total, precision: 5, scale: 2
  #t.decimal :data_share_total, precision: 6, scale: 2
  #t.decimal :surcharges_total, precision: 6, scale: 2
  #t.decimal :subtotal, precision: 6, scale: 2
  
  before_create :update_bill
  before_update :update_bill
  
  validates :amount, presence: true, 
    :numericality => { :greater_than_or_equal_to => 0, :less_than => 10000 }
  validates :total_data, presence: true, 
    :numericality => { :greater_than_or_equal_to => 0, :less_than => 1000 }
  validates :data_cost, presence: true, 
    :numericality => { :greater_than_or_equal_to => 0, :less_than => 10000 }
  
  belongs_to :account
  has_many :charges, dependent: :destroy
  
  private
  
  def update_bill
    data_subtotal = percent_total = data_share_total = 
    surcharges_total = subtotal = 0.0
    balance = self.amount
    if self.charges.present?
      self.charges.each do |charge|
        data_subtotal += charge.data_used
        percent_total += charge.data_percentage
        data_share_total += charge.data_share
        surcharges_total += charge.surcharges
        subtotal += charge.personal_total
        if charge.paid
          balance -= charge.personal_total
        end
      end
      percent_total *= 100
    end
    self.balance = balance
    self.data_subtotal = data_subtotal
    self.percent_total = percent_total
    self.data_share_total = data_share_total
    self.surcharges_total = surcharges_total
    self.subtotal = subtotal
  end
end

app/controllers/bills_controller.rb
class BillsController < ApplicationController
    before_action :authenticate_account!, only: [:show, :new, :create, 
      :edit, :destroy]
    before_action :correct_account, only: [:show, :edit, :update, :destroy, 
      :send_bill]
    
    
  def index
    if account_signed_in?
      @bills = Bill.where(:account_id => current_account.id).order(date: :desc).page(params[:page])
      @users = User.where(:account_id => current_account.id)
    end
  end
  
  def new
    @bill = Bill.new
  end
  
  def create
    @bill = Bill.new(bill_params)
    if @bill.save
      redirect_to @bill
    else
      render 'new'
    end
  end
  
  def show
    find_bill
    @charges = @bill.charges.order("created_at ASC")
  end
  
  def edit
    find_bill
  end
  
  def update
    find_bill
    if @bill.update_attributes(bill_params)
      flash[:success] = "Bill updated!"
      redirect_to @bill
    else
      render 'edit'
    end
  end
  
  def destroy
    find_bill
    @bill.destroy
    flash[:success] = "Bill deleted!"
    redirect_to bills_url
  end
  
  def send_bill
    find_bill
    BillMailer.mail_summary(@bill, current_account).deliver_later
    @bill.charges.each do |charge|
      if charge.user.a_manager?
        BillMailer.manager_bill(@bill, charge).deliver_later
      elsif charge.user.manager_id.present?
        # don't send stuff to managed user
      else
        BillMailer.mail_bill(@bill, charge).deliver_later
      end
    end
    flash[:success] = "Bill sent!"
    redirect_to root_path_url
  end
  
  private
    
    def bill_params
      params.require(:bill).permit(:date, :amount, :total_data, 
        :data_cost, :account_id, :data_overage)
    end
    
    def correct_account
      find_bill
      unless (@bill.account_id == current_account.id)
          flash[:danger]="That bill doesn't belong to you!"
          redirect_to root_path_url
      end
    end
    
    def find_bill
      @bill = Bill.find(params[:id])
    end
end

app/helpers/bills_helper.rb
module BillsHelper
  
  def get_class(charge_total, bill_total)
    if charge_total == bill_total
      return "text-success"
    else
      return "text-danger"
    end
  end
end

app/views/bills/_bill.html.erb
<tr> 
  <td><%= link_to bill.date.strftime("%B %Y"), bill, id: "bill-#{bill.id}" %></td>
  <td><%= bill.total_data %> GB</td>
  <td><%= number_to_currency(bill.amount) %></td>
  <td id="bill-balance-<%= bill.id %>">
    <%= number_to_currency(bill.balance) %>
  </td>
</tr>

app/views/bills/edit.html.erb
<% # bills/edit %>
<div class="container">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <h1 class="text-center">Edit Bill</h1>
      <%= form_for @bill do |f| %>
      <%= render "shared/form_errors", item: @bill %>
        <div class="form-group">
          <%= f.label "Date from Bill:" %>
          <%= f.date_select(:date, discard_day: true) %>
        </div>
        <div class="form-group">
          <%= f.label "Total amount of Bill:" %>
          <%= f.text_field :amount, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label "Total amount of Data used:" %>
          <%= f.text_field :total_data, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label "Total cost for Data:" %>
          <%= f.text_field :data_cost, class: "form-control" %>
        </div>
        <%= f.submit "Update Bill", class: 'btn btn-success pull-left' %>
      <% end %>
      <%= link_to "Cancel", :back, class: "btn btn-default pull-right" %>
    </div>
  </div>
</div>

app/views/bills/index.html.erb
<% if account_signed_in? %>
  <div class="container">
      <div class="row">
          <div class="col-md-6 col-md-offset-3">
              <h1 class="text-center">Bills Dashboard</h1>
              <% if @bills.present? %>
                <%= bill_total_by_month %>
              <% end %>
              <%= link_to "New Bill", new_bill_url, class: "btn btn-primary" %>
              <% if @bills.present? %>
                <table class="table table-striped">
                  <thead>
                   <tr class="text-center">
                     <th>Date</th>
                     <th>Data Used</th>
                     <th>Bill Total</th>
                     <th>Balance</th>
                   </tr>
                  </thead>
                  <tbody>
                   <%= render @bills %>
                  </tbody>
                </table>
                <%= paginate @bills %>
              <% else %>
                <p><br>You haven't created any bills yet.</p>
              <% end %>
              <% unless @users.present? %>
                <br>
                <p>Get started by adding your plan members on the Users tab at the top.</p>
              <% end %>
          </div>
      </div>
  </div>
<% else %>
  <div class="container">
      <div class="row">
        <div class="jumbotron">
          <h1 class="text-center">BillShare</h1>
          <h3 class="text-center">The easy way to split your phone bill</h3>
        </div>
        <div class="col-md-4 col-md-offset-4">
          <h3 class="text-center">How easy?</h3>
          <ol>
            <li>Add your plan members.</li>
            <li>Fill in a few details from your bill.</li>
            <li>Send a personalized email to each of your members with their 
                share of the bill.</li>
            <li>Track who's paid and who still owes you.</li>
            <li>Review your history as beautiful graphs.</li>
          </ol>
          <br/>
          <%= link_to "Get Started", new_account_registration_url, class: "btn btn-primary center-block" %>
          <br/>
          <p class="text-center">Already have an account?</p>
          <%= link_to "Sign In", new_account_session_url, class: "btn btn-primary center-block" %>
        </div>
      </div>
    </div>
<% end %>

app/views/bills/new.html.erb
<% # bills/new %>
<div class="container">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <h1 class="text-center">New Bill</h1>
      <%= form_for @bill do |f| %>
        <%= render "shared/form_errors", item: @bill %>
        <div class="form-group">
          <%= f.label "Date from Bill:" %>
          <%= f.date_select(:date, discard_day: true) %>
        </div>
        <div class="form-group">
          <%= f.label "Total amount of Bill:" %>
          <%= f.text_field :amount, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label "Total amount of Data used:" %>
          <%= f.text_field :total_data, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label "Total cost for Data:" %>
          <%= f.text_field :data_cost, class: "form-control" %>
        </div>
        <%= f.hidden_field :account_id, :value => current_account.id %>
        <%= f.submit "Start Bill", class: "btn btn-success pull-left" %>
      <% end %>
        <%= link_to "Cancel", :back, class: "btn btn-default pull-right" %>
    </div>
  </div>
</div>

app/views/bills/show.html.erb
<% # bills/show %>
<div class="container">
  <div class="row">
    <div class="col-md-10 col-md-offset-1">
      <h1 class="text-center"><%= @bill.date.strftime("%B %Y") %> Bill</h1>
      <%= link_to "Edit Bill Header", edit_bill_url(params[:id]), 
          class: "btn btn-primary" %>
      <%= link_to "Delete Bill", bill_path(params[:id]), method: :delete, 
          class: "btn btn-danger pull-right", 
          data: { confirm: "Delete this Bill?" } %>
      <table class="table table-hover">
        <thead>
          <tr class="text-center">
            <th>Date</th>
            <th>Data Used</th>
            <th>Data Fee</th>
            <th>Bill Total</th>
            <th>Balance</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td><%= @bill.date.strftime("%B %Y") %></td>
            <td><%= @bill.total_data %> GB</td>
            <td><%= number_to_currency(@bill.data_cost) %></td>
            <td><%= number_to_currency(@bill.amount) %></td>
            <td id="bill-balance">
              <%= number_to_currency(@bill.balance) %>
            </td>
          </tr>
        </tbody>
      </table>
      <%= link_to "Add User Charge", new_bill_charge_url(params[:id]), 
          class: "btn btn-primary" %>
      <br><br>
      <table class="table table-bordered table-striped">
        <thead>
          <tr>
            <th>User</th>
            <th>Data Used</th>
            <th>% of Data</th>
            <th>Data Fee</th>
            <th>Surcharges</th>
            <th>User Total</th>
            <th>Status</th>
            <th class="text-center">Edit</th>
          </tr>
        </thead>
        <tbody>
          <%= render @charges, selector: "long" %>
          <tr>
            <th>Totals</th>
            <td class=<%= get_class(@bill.data_subtotal, @bill.total_data)%>
              id="data-subtotal">
              <%= @bill.data_subtotal %> GB
            </td>
            <td class=<%= get_class(@bill.percent_total, 100.0) %>
              id="percent-total">
              <%= @bill.percent_total %>%
            </td>
            <td class=<%= get_class(@bill.data_share_total, @bill.data_cost)%>
              id="data-share-total">
              <%= number_to_currency(@bill.data_share_total) %>
            </td>
            <td class=<%= get_class(@bill.surcharges_total, 
              @bill.amount - @bill.data_cost) %> id="surcharges-total">
              <%= number_to_currency(@bill.surcharges_total) %>
            </td>
            <td class=<%= get_class(@bill.subtotal, @bill.amount) %>
              id="subtotal">
              <%= number_to_currency(@bill.subtotal) %></td>
            <td class="text-center">-</td>
            <td class="text-center">-</td>
          </tr>
        </tbody>
      </table>
      <%= link_to "Send Bill", send_bill_url, 
        class: "btn btn-primary pull-right", 
        data: { confirm: "Ready to send?" } %>
    </div>
  </div>
</div>