config/routes.rb
Rails.application.routes.draw do
  
  root 'bills#index', as: 'root_path'
  
  devise_for :accounts, :controllers => {registrations: 'registrations' }
  
  resources :users
  resources :bills do
    resources :charges, only: [:create, :new, :edit, :update, :destroy]
  end
  get 'bills/:id/send', to: 'bills#send_bill', as: :send_bill
  get 'users/:id/send', to: 'users#send_reminder', as: :send_reminder
  get 'settings', to: 'accounts#settings', as: :settings
  get 'reports', to: 'accounts#reports', as: :reports
  
  resources :charts, only: [] do
    collection do
      get 'bill_total_by_month'
      get 'user_charge_chart'
      get 'user_balance_chart'
    end
  end
  
end

app/models/charge.rb
class Charge < ActiveRecord::Base
  #t.references :bill, index: true, foreign_key: true
  #t.references :user, index: true, foreign_key: true
  #t.references :account, index: true, foreign_key: true, null: false
  #t.decimal :surcharges, precision: 6, scale: 2
  #t.decimal :data_used, precision: 6, scale: 3
  #t.decimal :data_percentage, precision: 4, scale: 2
  #t.decimal :data_share, precision: 6, scale: 2
  #t.decimal :personal_total, precision: 6, scale: 2
  #t.boolean :paid
  #t.date :date
  
  before_create :get_data_percentage, :get_data_share, :get_personal_total,
    :get_date
  after_create :set_user_balance, :update_bill
  
  before_update :get_data_percentage, :get_data_share, :get_personal_total,
    :get_date
  after_update :set_user_balance, :update_bill
  
  after_destroy :update_bill, :set_user_balance
    
  validates :user_id, presence: true
  validates :surcharges, presence: true, 
    :numericality => { :greater_than_or_equal_to => 0, :less_than => 10000 }
  validates :data_used, presence: true, 
    :numericality => { :greater_than_or_equal_to => 0, :less_than => 1000 }
  
  belongs_to :bill
  belongs_to :user
  belongs_to :account
  
  private
  
    def get_data_percentage
      self.data_percentage = data_used / bill.total_data.to_d
    end
    
    def get_data_share
      self.data_share = data_percentage.to_d * bill.data_cost.to_d
    end
    
    def get_personal_total
      self.personal_total = data_share.to_d + surcharges.to_d
    end
    
    def get_date
      self.date = bill.date
    end
    
    def set_user_balance
      balance = 0.00
      user.charges.each do |charge|
        unless charge.paid
          balance += charge.personal_total
        end
      end
      user.update_attributes(:balance => balance)
    end
    
  def update_bill
    data_subtotal = percent_total = data_share_total = 
    surcharges_total = subtotal = 0.0
    balance = bill.amount
    if bill.charges.present?
      bill.charges.each do |charge|
        data_subtotal += charge.data_used
        percent_total += charge.data_percentage
        data_share_total += charge.data_share
        surcharges_total += charge.surcharges
        subtotal += charge.personal_total
        if charge.paid
          balance -= charge.personal_total
        end
      end
      percent_total *= 100
    end
    bill.update_attributes(
      :balance => balance, :data_subtotal => data_subtotal,
      :percent_total => percent_total, :data_share_total => data_share_total,
      :surcharges_total => surcharges_total, :subtotal => subtotal)
  end
    
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
   before_action :authenticate_account!
   before_action :correct_account, only: [:edit, :destroy, :update, :mark_paid]
  
  def new
    @charge = Charge.new
  end
  
  def create
    @charge = Charge.new(charge_params)
    if @charge.save
      flash[:success] = "Charge added!"
      redirect_to bill_url(params[:bill_id])
    else
      render 'new'
    end
  end
  
  def edit
    find_charge
  end
  
  def update
    find_charge
    if @charge.update_attributes(charge_params)
        flash[:success] = "Charge updated!"
        redirect_to :back
    else
        render 'edit'
    end
  end
  
  def destroy
    find_charge
    @charge.destroy
    flash[:success] = "Charge deleted!"
    redirect_to bill_url(params[:bill_id])
  end
    
  private
  
  def charge_params
    params.require(:charge).permit(:user_id, :surcharges, :data_used, 
        :account_id, :bill_id, :paid, :data_percentage, :data_share, 
        :personal_total)
  end
  
  def correct_account
      find_charge
      unless @charge.account_id == current_account.id
        flash[:warning]="That charge doesn't belong to you!"
        redirect_to root_path_url
      end
  end
  
  def find_charge
      @charge = Charge.find_by(:bill_id => params[:bill_id], :id => params[:id])
  end
end

app/helpers/charges_helper.rb
module ChargesHelper
  
  def paid_boolean(charge)
    if charge.paid
      "paid"
    else
      "unpaid"
    end
  end
  
end

app/views/charges/_charge.html.erb
<tr>
  <% if selector == "email" %>
    <td style="border: 1px solid black; padding: 5px; text-align: right;">
     <%= charge.date.strftime( "%b %Y") %>
    </td>
    <td style="border: 1px solid black; padding: 5px; text-align: right;">
     <%= charge.data_used %> GB
    </td>
    <td style="border: 1px solid black; padding: 5px; text-align: right;">
     <%= number_to_currency(charge.personal_total) %>
    </td>
  <% elsif selector == "short" %>
    <td><%= link_to charge.date.strftime("%B %Y"), charge.bill %></td>
    <td><%= charge.data_used %> GB</td>
    <td><%= number_to_currency(charge.personal_total) %></td>
    <td><%= link_to paid_boolean(charge), 
      bill_charge_path(charge: { :paid => !charge.paid }, bill_id: charge.bill_id, id: charge.id ), 
      method: :patch, remote: true %></td>
  <% else %>
    <td><%= link_to charge.user.name, charge.user %></td>
    <td><%= charge.data_used %> GB</td>
    <td><%= charge.data_percentage * 100 %>%</td>
    <td><%= number_to_currency(charge.data_share) %></td>
    <td><%= number_to_currency(charge.surcharges) %></td>
    <td><%= number_to_currency(charge.personal_total) %></td>
    <td><%= link_to paid_boolean(charge), 
      bill_charge_path(charge: { :paid => !charge.paid }, bill_id: charge.bill_id, id: charge.id ), 
      method: :patch %></td>
      <td class="text-center"><%= link_to "", edit_bill_charge_url(bill_id: params[:id], id: charge.id),
        class: "glyphicon glyphicon-cog", id: "edit-charge-#{charge.id}" %></td>
  <% end %>
</tr>

app/views/charges/edit.html.erb
<% #charges/edit %>
<div class="container">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <h1 class="text-center">Edit Charge</h1>
      <div class="form-group">
        <%= link_to "Delete Charge", bill_charge_path(params[:bill_id], 
              params[:id]), method: :delete, class: "btn btn-danger pull-right", 
              data: { confirm: "Delete charge?" } %>
      </div>
      <%= form_for @charge, url: bill_charge_path(params[:bill_id], 
            params[:id]), html: { method: :patch }  do |f| %>
        <%= render "shared/form_errors", item: @charge %>
        <div class="form-group">
          <%= f.label :user %>
          <%= f.select(:user_id, User.where(:account_id => current_account.id).collect {|p| [ p.name, p.id ] }, {include_blank: ""}) %>
        </div>
        <div class="form-group">
          <%= f.label :surcharges %>
          <%= f.text_field :surcharges, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :data_used %> <b> (GB)</b>
          <%= f.text_field :data_used, class: "form-control" %>  
        </div>
        <%= f.hidden_field :account_id, :value => current_account.id %>
        <%= f.hidden_field :bill_id, :value => params[:bill_id] %>
        <%= f.hidden_field :paid, :value => false %>
        <%= f.submit class: "btn btn-success pull-left" %>
        <%= link_to "Cancel", bill_path(params[:bill_id]), class: "btn btn-default pull-right" %>
      <% end %>
    </div>
  </div>
</div>

app/views/charges/new.html.erb
<% #charges/new %>
<div class="container">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <h1 class="text-center">New Charge</h1>
      <%= form_for @charge, url: bill_charges_path(params[:bill_id]), 
          html: { method: :post }  do |f| %>
        <%= render "shared/form_errors", item: @charge %>
        <div class="form-group">
          <%= f.label :user %>
          <%= f.select(:user_id, User.where(:account_id => current_account.id).collect {|p| [ p.name, p.id ] }, {include_blank: ""}) %>
        </div>
        <div class="form-group">
          <%= f.label :surcharges %>
          <%= f.text_field :surcharges, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :data_used %> <b> (GB)</b>
          <%= f.text_field :data_used, class: "form-control" %>  
        </div>
        <%= f.hidden_field :account_id, :value => current_account.id %>
        <%= f.hidden_field :bill_id, :value => params[:bill_id] %>
        <%= f.hidden_field :paid, :value => false %>
        <%= f.submit class: "btn btn-success" %>
        <%= link_to "Cancel", :back, class: "btn btn-default pull-right" %>
      <% end %>
    </div>
  </div>
</div>