config/routes.rb
Rails.application.routes.draw do
  
  root 'bills#index', as: 'root_path'
  
  devise_for :accounts, :controllers => {registrations: 'registrations' }
  
  resources :users
  resources :bills do
    resources :charges, only: [:create, :new, :edit, :update, :destroy]
  end
  get 'bills/:id/send', to: 'bills#send_bill', as: :send_bill
  get 'users/:id/send', to: 'users#send_reminder', as: :send_reminder
  get 'settings', to: 'accounts#settings', as: :settings
  get 'reports', to: 'accounts#reports', as: :reports
  
  resources :charts, only: [] do
    collection do
      get 'bill_total_by_month'
      get 'user_charge_chart'
      get 'user_balance_chart'
    end
  end
  
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-custom">
  <div class="container-fluid">
    <div class="navbar-header">
        <%= link_to root_path_url, class:"navbar-brand" do %>
        <b><i>BillShare</i></b> <% end %>
    </div>
    
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <% if account_signed_in? %>
        <ul class="nav navbar-nav">
          <li><%= link_to users_url do %>
            <span class="glyphicon glyphicon-user"></span> Users
            <% end %>
          </li>
        </ul>
      <% end %>
      
      <ul class="nav navbar-nav navbar-right">
        <% if account_signed_in? %>
          <li><%= link_to edit_account_registration_url do %>
            <span class="glyphicon glyphicon-cog"></span> Settings</li>
            <% end %>
          <li><%= link_to destroy_account_session_path, method: :delete do %>
            <span class="glyphicon glyphicon-log-out"></span> Logout</li>
            <% end %>
        <% else %>
          <li><%= link_to "Register", new_account_registration_url %></li>
          <li><%= link_to "Login", new_account_session_url %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navbar.js.erb
$('.nav.navbar-nav > li').on('click', function(e) {
    $('.nav.navbar-nav > li').removeClass('active');
    $(this).addClass('active');
});   

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BillShare</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag "https://www.google.com/jsapi" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/navbar' %>
  <%= flash_messages %>
  <%= yield %>
</body>
</html>